# Generated by Django 4.2.7 on 2023-12-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_name',
            field=models.CharField(default='Placeholder', max_length=256, verbose_name='Article Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
