# Generated by Django 4.2.7 on 2023-12-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_first',
            field=models.ImageField(height_field=618, upload_to='static/', width_field=1000),
        ),
    ]
