# Generated by Django 4.2.7 on 2023-12-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_image_first'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_first',
            field=models.ImageField(height_field='618px', upload_to='../CMS/static/', width_field='1000px'),
        ),
    ]
