# Generated by Django 4.2.7 on 2023-12-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_article_image_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author_name',
            field=models.CharField(default='Cps', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_img',
            field=models.ImageField(default='do zmiany', upload_to='../CMS/static/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='image_first',
            field=models.ImageField(upload_to='../CMS/static/'),
        ),
    ]
