# Generated by Django 4.2.7 on 2023-12-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_article_image_first'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_first',
            field=models.ImageField(upload_to=''),
        ),
    ]
